-- Migration: create public.bot_outbox table for admin outbox messages

-- 1) Table
create table if not exists public.bot_outbox (
                                                 id bigint generated by default as identity primary key,
                                                 telegram_chat_id bigint not null,
                                                 text text not null,
                                                 admin_uid uuid,
                                                 status text not null default 'pending',
                                                 created_at timestamptz not null default now(),
    sent_at timestamptz null,
    error_message text null
    );

-- 2) Enable RLS
alter table public.bot_outbox enable row level security;

-- 3) Policies (safe recreate)
drop policy if exists "outbox select for authenticated" on public.bot_outbox;
create policy "outbox select for authenticated"
  on public.bot_outbox
  for select
                      to authenticated
                      using (true);

drop policy if exists "outbox insert for authenticated" on public.bot_outbox;
create policy "outbox insert for authenticated"
  on public.bot_outbox
  for insert
  to authenticated
  with check (true);

-- 4) Optional: service role (worker)
drop policy if exists "outbox update by service_role" on public.bot_outbox;
create policy "outbox update by service_role"
  on public.bot_outbox
  for update
                                  to service_role
                                  using (true)
      with check (true);
